# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: RouxAntoine/checkout@v4.1.8
    # - uses: deavmi/setup-dlang@patch-1

    - name: Install D compiler and Dub
      run: |
          apt update
          # curl -fsS https://dlang.org/install.sh | bash -s dmd
          # apt install default-d-compiler -y
          apt install gdc -y
          apt install dub -y

    - name: Install Doveralls (code coverage tool)
      run: |
          dub fetch doveralls
          apt update
          apt install libcurl4-openssl-dev -y

    - name: 'Build & Test'
      run: |
        # Explicitly set the compiler to `gdc`
        DC=gdc

        # Build the project, with its main file included, without unittests
        dub build --compiler=$DC
        # Build and run tests, as defined by `unittest` configuration
        # In this mode, `mainSourceFile` is excluded and `version (unittest)` are included
        # See https://dub.pm/package-format-json.html#configurations
        dub test --compiler=$DC --coverage

    - name: Coverage upload
      run: |
          dub run doveralls -- -t ${{secrets.COVERALLS_REPO_TOKEN}}
